// Package metrics defines all Prometheus metrics used across EDI simulator services.
// Import this package in any service and call the exported variables directly.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// MessagesProcessedTotal counts messages handled, labelled by service, EDI format and outcome.
	MessagesProcessedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "edi_messages_processed_total",
		Help: "Total number of EDI messages processed.",
	}, []string{"service", "format", "status"})

	// MessageProcessingDuration is a histogram of per-message processing time.
	MessageProcessingDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "edi_message_processing_duration_seconds",
		Help:    "Histogram of message processing durations in seconds.",
		Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
	}, []string{"service"})

	// QueueDepth is a live gauge of messages sitting in each RabbitMQ queue.
	// Updated by the API gateway's background queue-depth poller.
	QueueDepth = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "edi_queue_depth",
		Help: "Current number of messages waiting in each queue.",
	}, []string{"queue"})

	// TransformationsTotal counts EDI format transformations by direction and outcome.
	TransformationsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "edi_transformations_total",
		Help: "Total number of EDI format transformations attempted.",
	}, []string{"source_format", "target_format", "status"})

	// HTTPRequestsTotal counts all requests serviced by the API gateway.
	HTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "edi_http_requests_total",
		Help: "Total HTTP requests received by the API gateway.",
	}, []string{"method", "path", "status_code"})

	// HTTPRequestDuration tracks API gateway request latency.
	HTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "edi_http_request_duration_seconds",
		Help:    "Histogram of HTTP request durations in seconds.",
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
	}, []string{"method", "path"})

	// DLQMessagesTotal counts messages sent to dead-letter queues.
	DLQMessagesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "edi_dlq_messages_total",
		Help: "Total messages routed to dead-letter queues.",
	}, []string{"service", "queue"})

	// SimulatorMessagesTotal counts messages generated by the simulator.
	SimulatorMessagesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "edi_simulator_messages_total",
		Help: "Total messages generated by the simulator service.",
	}, []string{"format", "malformed"})
)
